extends: "common"

apply:
  - "local"

auth:
  merge:
    jwtIssuer: "example.com"
    jwksEndpoint: "https://example.com/.well-known/jwks.json"

cors:
  merge:
    hosts:
      - { host: "localhost:3000", scheme: "http" }

sql:
  merge:
    jdbcUrl: "jdbc:postgresql://localhost/kairo_sample"
    username: ~
    password: ~

sqlMigration:
  merge:
    run: true
    cleanOnValidationError: true
